[General]
bypass-system = true
dns-server = https://dns.adguard-dns.com/dns-query
dns-fallback = https://cloudflare-dns.com/dns-query,https://dns.google/dns-query
dns-direct-system = false
dns-direct-fallback = https://cloudflare-dns.com/dns-query,https://dns.google/dns-query
ipv6 = false

[Rule]
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/misc.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/canva.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/kinopub.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/news.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/torrents.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/airbnb.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/facetime.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/hostings.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/signal.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Yandex/Yandex.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Whatsapp/Whatsapp.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Copilot/Copilot.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Gemini/Gemini.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Anthropic/Anthropic.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Claude/Claude.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Twitter/Twitter.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Instagram/Instagram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Facebook/Facebook.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/LinkedIn/LinkedIn.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/BBC/BBC.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Jetbrains/Jetbrains.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Discord/Discord.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Speedtest/Speedtest.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Game/Roblox/Roblox.list,PROXY
RULE-SET,https://raw.githubusercontent.com/zeklop/shadowrocket-configs/main/REJECT.list,REJECT
FINAL,DIRECT
