[General]
bypass-system = true
dns-server = https://cloudflare-dns.com/dns-query
dns-fallback = https://dns.google/dns-query
dns-direct-system = false
dns-direct-fallback = https://cloudflare-dns.com/dns-query
ipv6 = true
prefer-ipv6 = false

[Proxy Group]
AUTO = url-test,LOCAL-SERVERS,interval=600,tolerance=100,timeout=5,url=https://cp.cloudflare.com/generate_204

[Rule]
DOMAIN-SUFFIX,2ip.ru,AUTO
DOMAIN-SUFFIX,2ip.io,DIRECT
DOMAIN-SUFFIX,gemini.google.com,AUTO
DOMAIN-SUFFIX,gemini.google,AUTO
DOMAIN-SUFFIX,crazypanda.ru,DIRECT
DOMAIN-SUFFIX,crazypanda.games,DIRECT
DOMAIN-SUFFIX,unity3d.com,DIRECT
DOMAIN-SUFFIX,4pda.to,AUTO
DOMAIN-SUFFIX,adguard.org,AUTO
DOMAIN-SUFFIX,adguard.com,AUTO
DOMAIN-SUFFIX,nike.com,AUTO
DOMAIN-SUFFIX,newbalance.com,AUTO
DOMAIN-SUFFIX,levi.com,AUTO
DOMAIN-SUFFIX,adidas.com,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/canva.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/chatgpt.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/claude.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/copilot.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/discord.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/facebook.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/grok.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/instagram.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/jetbrains.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/kinopub.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/linkedin.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/news.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/telegram.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/torrents.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/voice-ports.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/whatsapp.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/refs/heads/main/rules/youtube.list,AUTO
FINAL,DIRECT
