[General]
bypass-system = true
dns-server = https://cloudflare-dns.com/dns-query
dns-fallback = https://dns.google/dns-query
dns-direct-system = false
dns-direct-fallback = https://cloudflare-dns.com/dns-query
ipv6 = false

[Rule]
DOMAIN-SUFFIX,2ip.ru,PROXY
DOMAIN-SUFFIX,4pda.to,PROXY
DOMAIN-SUFFIX,adguard.org,PROXY
DOMAIN-SUFFIX,adguard.com,PROXY
DOMAIN-SUFFIX,adguard.info,PROXY
DOMAIN-SUFFIX,adtidy.org,PROXY
DOMAIN-SUFFIX,nike.com,PROXY
DOMAIN-SUFFIX,newbalance.com,PROXY
DOMAIN-SUFFIX,x.ai,PROXY
DOMAIN-SUFFIX,ufc.com,PROXY
DOMAIN-SUFFIX,ufcfightpass.com,PROXY
DOMAIN-SUFFIX,ufcespanol.com,PROXY
DOMAIN-SUFFIX,ufc.tv,PROXY
DOMAIN-SUFFIX,savefrom.net,PROXY
DOMAIN-SUFFIX,sf-tools.com,PROXY
DOMAIN-SUFFIX,sf-converter.com,PROXY
DOMAIN-SUFFIX,qrcode-alligator.com,PROXY
DOMAIN-SUFFIX,grammarly.com,PROXY
DOMAIN-SUFFIX,aistudio.google.com,PROXY
DOMAIN-SUFFIX,alkalimining-pa.googleapis.com,PROXY
DOMAIN-SUFFIX,yamilov.com,PROXY
DOMAIN-SUFFIX,habr.com,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/canva.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/kinopub.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/news.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/torrents.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/airbnb.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/facetime.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/hostings.list,PROXY
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/olympics.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Whatsapp/Whatsapp.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Copilot/Copilot.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Gemini/Gemini.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Anthropic/Anthropic.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Claude/Claude.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Twitter/Twitter.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Instagram/Instagram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Facebook/Facebook.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/LinkedIn/LinkedIn.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/BBC/BBC.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Jetbrains/Jetbrains.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Discord/Discord.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Speedtest/Speedtest.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Game/Roblox/Roblox.list,PROXY
RULE-SET,https://raw.githubusercontent.com/zeklop/shadowrocket-configs/main/REJECT.list,REJECT
FINAL,DIRECT
