[General]
bypass-system = true
dns-server = https://cloudflare-dns.com/dns-query
dns-fallback = https://dns.google/dns-query
dns-direct-system = false
dns-direct-fallback = https://cloudflare-dns.com/dns-query
ipv6 = false

[Proxy Group]
TRUSTED = url-test,LOCAL-SERVERS,interval=600,tolerance=100,timeout=5,url=https://cp.cloudflare.com/generate_204
PUBLIC-B = url-test,PUB-BLACK-SUB,interval=3600,tolerance=100,timeout=5,url=https://cp.cloudflare.com/generate_204
PUBLIC-W = url-test,PUB-WHITE-SUB,interval=3600,tolerance=100,timeout=5,url=https://cp.cloudflare.com/generate_204
AUTO = fallback,TRUSTED,PUBLIC-B,PUBLIC-W,policy-select-name=TRUSTED,interval=600,timeout=5,url=https://cp.cloudflare.com/generate_204

[Rule]
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/misc.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/canva.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/kinopub.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/news.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/torrents.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/airbnb.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/facetime.list,AUTO
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/hostings.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Whatsapp/Whatsapp.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Copilot/Copilot.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Gemini/Gemini.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Anthropic/Anthropic.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Claude/Claude.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Twitter/Twitter.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Instagram/Instagram.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Facebook/Facebook.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/LinkedIn/LinkedIn.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/BBC/BBC.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Jetbrains/Jetbrains.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Discord/Discord.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Speedtest/Speedtest.list,AUTO
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Game/Roblox/Roblox.list,AUTO
RULE-SET,https://raw.githubusercontent.com/zeklop/shadowrocket-configs/main/REJECT.list,REJECT
FINAL,DIRECT
