[General]
bypass-system = true
dns-server = https://cloudflare-dns.com/dns-query
dns-fallback = https://dns.google/dns-query
dns-direct-system = false
dns-direct-fallback = https://cloudflare-dns.com/dns-query
ipv6 = false

[Proxy Group]
AUTO = url-test,LOCAL-SERVERS,interval=600,tolerance=100,timeout=5,url=https://cp.cloudflare.com/generate_204

[Rule]
RULE-SET,https://raw.githubusercontent.com/eyamilov/sr-conf/main/rules/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/zeklop/shadowrocket-configs/main/REJECT.list,REJECT
FINAL,AUTO
