# Test conf. Do not use
[General]
bypass-system = true
dns-server = system
ipv6 = true

[Proxy]
MyProxy = vmess, example.com, 443, username=uuid-here, tls=true

[Proxy Group]
Proxy = select, MyProxy, direct

[Rule]
DOMAIN-SUFFIX,youtube.com,Proxy
DOMAIN-SUFFIX,googlevideo.com,Proxy
DOMAIN-SUFFIX,whatsapp.com,Proxy
DOMAIN-SUFFIX,whatsapp.net,Proxy
FINAL,direct

[Host]
