[General]
bypass-system = true
dns-server = https://cloudflare-dns.com/dns-query,https://dns.google/dns-query
dns-fallback = system
dns-direct-system = false
dns-direct-fallback = system
ipv6 = false

[Proxy Group]
TRUSTED = url-test,LOCAL-SERVERS,interval=600,tolerance=100,timeout=5,url=https://cp.cloudflare.com/generate_204
PUBLIC-B = url-test,PUB-BLACK-SUB,interval=3600,tolerance=100,timeout=5,url=https://cp.cloudflare.com/generate_204
PUBLIC-W = url-test,PUB-WHITE-SUB,interval=3600,tolerance=100,timeout=5,url=https://cp.cloudflare.com/generate_204
AUTO = fallback,TRUSTED,PUBLIC-B,PUBLIC-W,policy-select-name=TRUSTED,interval=600,timeout=5,url=https://cp.cloudflare.com/generate_204

[Rule]
FINAL,AUTO
